server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3308/layout
      username: bg_admin
      password: bg_admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 500
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1
      validation-query-timeout: 200
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
  redis:
    host: 127.0.0.1      # Redis服务器地址
    port: 6379           # 端口
    password:            # 密码（无密码则留空）
    database: 0          # 数据库索引
    lettuce:
      pool:
        max-active: 8   # 最大连接数
        max-idle: 8      # 最大空闲连接
        min-idle: 1      # 最小空闲连接
        max-wait: 100ms  # 连接等待时间
    timeout: 5000ms
mybatis:
  #标注mapper文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #类型扫描包 可简化mapper.xml中类型的书写
  type-aliases-package: com.yzr.resource.layout.background.dao.entity
  configuration:
    #字段驼峰自动映射开启
    map-underscore-to-camel-case: true
secretKey: 'layoutBackground' #token 加密秘钥